### ISSUE TITLE
Branches for  solana version 1.11,1.12,1.13....

### ISSUE THREAD

**Issue by SushantChandla** [halbornteam/solana-test-framework#3]
Just like the solana1.10 branch. Can you guys add the other branches

**Comment by hiddengearz** [comment]
Sure, I'll update this issue once completed.

**Comment by hiddengearz** [comment]
We have a dependency on [anchor-lang](https://docs.rs/crate/anchor-lang) which doesn't have a version that supports 1.11, 1.12 or 1.13. Gonna have to figure out a workaround...

**Comment by hiddengearz** [comment]
Support for Solana 1.11, 1.12 and 1.13 has been added. Please switch to the appropriate branch.
